pipeline:
  name: test-2
  identifier: test2
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1761129192082
        repoName: test-nodejs-app
        build: <+input>
  stages:
    - stage:
        name: clone
        identifier: clone
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: VM
            spec:
              type: Pool
              spec:
                poolName: ubuntu-gcp
                os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: echo "hello world"
        delegateSelectors:
          - docker-delegate
        when:
          pipelineStatus: Success
